version: '3'
services:
  wolfie:
    image: aquerr/wolfie:latest
    user: wolfie
    ports:
      - "8087:8087"
    volumes:
      - ./config:/opt/app/config
      - ./data:/opt/app/data
      - ./logs:/opt/app/logs