services:
  wolfie:
    container_name: wolfie-bot
    restart: unless-stopped
    image: aquerr/wolfie:latest
    ports:
      - "8087:8087"
    volumes:
      - ./config:/opt/app/config
      - ./data:/opt/app/data
      - ./logs:/opt/app/logs