spring:
  application:
    name: wolfie

bot:
  discord:
    token: ???
    guild-id: ???
  front-end:
    url: ???
  evaluation:
    expiration-time: 1d
  roles:
    game-master:
      id: ???
  channels:
    summary:
      id: ???
    rank-change:
      id: ???

logging:
  file:
    name: ./logs/wolfie.log
  charset:
    file: UTF-8
  logback:
    rollingpolicy:
      max-file-size: 5MB
      total-size-cap: 50MB
      max-history: 10